# OLED 디스플레이 순정 활성화
CONFIG_ZMK_DISPLAY=y

# ZMK Studio (웹 GUI 실시간 편집기) 엔진 활성화
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 배터리 보존을 위한 자동 절전 모드 (5분 뒤 딥 슬립)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# LED 백라이트 하드웨어 라인 전력 원천 차단
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
