# OLED 디스플레이 순정 기본 활성화
CONFIG_ZMK_DISPLAY=y

# 배터리 관리를 위한 자동 절전 모드 (5분간 입력 없으면 초절전 딥 슬립)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# LED 백라이트 (RGB Underglow) 하드웨어 회로 전력 완천 차단 및 삭제
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
